
version: "3"

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    restart: on-failure
    volumes:
      - .:/dogane
    env_file:
      - .env
  
